image:
  file: Dockerfile
  
ports:
  - port: 8001
  
tasks:
  -  command: mkdir /workspace/iota.lib.cpp/logs                                                                    &&
              mkdir /workspace/iota.lib.cpp/openthread-all                                                          &&
              touch /workspace/iota.lib.cpp/logs/gitpod-install-log.txt                                             &&
       

              echo "Starting .gitpod.yml installation" &>>  /workspace/iota.lib.cpp/logs/gitpod-install-log.txt     &&
              
              git clone https://github.com/whoshuu/cpr.git                                                          &&
              git clone https://github.com/curl/curl.git                                                            &&
              git clone https://github.com/google/googletest.git                                                    &&
              git clone https://github.com/nlohmann/json.git                                                        &&
              git clone https://github.com/XKCP/XKCP.git                                                            &&
              
              
              
              echo "Starting Apache"                   &>>  /workspace/iota.lib.cpp/logs/gitpod-install-log.txt     &&   
              apachectl start                                                                                       &&
              gp preview $(gp url 8001)                                                                             &&
              
              
              echo "Ending .gitpod.yml installation"  &>>   /workspace/iota.lib.cpp/logs/gitpod-install-log.txt    
              
              
     
